cabal-version:       3.0

name:                gui
version:             0.1.0.0

author:              Patrick Bahr, Jean-Claude Sebastian Disch, Asger Lademark Heegaard
maintainer:          paba@itu.dk
build-type:          Simple

common shared-settings
  build-depends:
    WidgetRattus ^>=0.4,
    base ^>=4.17.2.1,
    containers,
    text,
    time,

  hs-source-dirs: src
  default-language: Haskell2010
  ghc-options: -W

executable flight
  import: shared-settings
  main-is: FlightBooker.hs

executable timer
  import: shared-settings
  main-is: Timer.hs

executable counter
  import: shared-settings
  main-is: Counter.hs

executable stopwatch
  import: shared-settings
  main-is: Stopwatch.hs

executable converter
  import: shared-settings
  main-is: TemperatureConverter.hs

executable calculator
  import: shared-settings
  main-is: Calculator.hs

executable rewrite
  import: shared-settings
  main-is: RewriteTests.hs

executable integral
  import: shared-settings
  main-is: IntegralTests.hs

executable derivative
  import: shared-settings
  main-is: DerivativeTests.hs
